#! /bin/sh
### BEGIN INIT INFO
# Provides:          butler-md
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Controls Pick Put Station
# Description:       
### END INIT INFO

# Author: Grey Orange <support@greyorange.sg>

# Do NOT "set -e"

DESC="UI"
NAME=butler_md_alpha
DAEMON=/opt/butler_md_alpha/bin/$NAME
DAEMON_ARGS=""
SCRIPTNAME=/etc/init.d/$NAME
DIR=`pwd`

if [ -z "$HOME" ]; then
	export HOME=/opt/butler_md_alpha
fi

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	 /opt/butler_md_alpha/bin/butler-md-alpha start
}

#
# Function that stops the daemon/service
#
do_stop()
{
	 /opt/butler_md_alpha/bin/butler-md-alpha stop
}


case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  restart|force-reload)
	do_stop
	do_start
	;;
 *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
	exit 3
	;;
esac

:
